### ISSUE TITLE
Level Selection Screen

### ISSUE THREAD

**Issue by torokpeter** [torokpeter/TowerDefense#18]
**Version:** Added when implemented
**Date:** 02-12-2018
**Importance:** High
**Feature:** Create the level selection screen such that the user will be able to see the general layout of the level and the description related to it. Possible idea is to create an ".xml" file containing all level names. On every load of the game update the ".xml" in case new levels were added. The levels should be stored in folders with the "levelname" as name. These folders should contain files such as "level.xml" - containing level details, "level.png" - the level layout in a smaller scale and possible other files that will later be added

**Comment by zsolt3991** [comment]
Done as of
d6621270c6e4ecb9a28a4f4547516f3a171e8959
